### PR TITLE
Partial restore feature

### PR DESCRIPTION
**Pull request by mknjc**
Add a zbackup restore-partial command, as mentioned in #105 and #121 

Example:
zbackup <params> restore-partial <backup> >/tmp/test <<EOF
0
1024
2048
1024
EOF

restores the first 1024 bytes and 1024 bytes at position 2048 into /tmp/test

I'm now started developing a backupcreator (#105) extension.

### CODE REVIEW

**Comment by davidbartonau** [comment]
Hi @mknjc,

Thanks for doing that.  

I like your use of the DataSink rather than the void pointer (ver Java-like!), but doesn't it then make sense to refactor saveData to use the new restore method?  Writing bytes out to a void\* seems to be a special case of a DataSink and that way we don't have two different restore paths.  Rewriting that core restore logic does seem a little scary, but your code does look like a copy and paste.

Reading the change in context, it actually looks like you could have a restore method that you pass in an Outputer, since the two Outputers are identical except for how they write data.

Also, your code doesn't build in Travis CI:
/home/travis/build/zbackup/zbackup/zutils.cc:307:22: error: ‘stoll’ is not a member of ‘std’

File: backup_restorer.cc [hunk 1]
```diff
@@ -315,4 +315,92 @@ void IndexedRestorer::saveData( int64_t offset, void * data, size_t size ) const
   }
 }
 
+void IndexedRestorer::restore( int64_t offset, DataSink * output, size_t size ) const
```
Comment (rutsky) [inline backup_restorer.cc:228]: This is almost exact copy of `saveData` method above.
Lets implement one using another, e.g. implement `saveData` using `restore` with custom DataSink.

**Comment by mknjc** [comment]
Usually I try to change as less code as possible in my pull request but if you're Easy with the change I'd love to rewrite the functions.

**Comment by mknjc** [comment]
The travis build fail caused through the old gcc used when building, is there a way to specify a newer version? Or should we stick zbackup to an obsolete c++ standard?

**Comment by davidbartonau** [comment]
Selfishly, I'd say it has to compile on Ubuntu 12.04 with the default gcc installed as I have a lot of machines running with that configuration.  Not sure about others opinions, but that compiler would be circa 2011.  IMHO any older than that seems excessive.

I can do a pull and see if it compiles with 12.04.

**Comment by mknjc** [comment]
You don't have to check it, travis is running 12.04
